name: Html 5 Validation

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at 00:00

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.4.0
      - name: Html 5 Validation.
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./
      - name: Run ESLint
        run: eslint js/*.js --ext .js